database:
  host: localhost
  port: 5432
  user: postgres
  password: root
  name: db_rex  

server:
  host: localhost
  port: 3333

jwt:
  secret: lee0Op9iriThai7mXae5ahxuUpo2thaenaeL6mooaehahk1U
  accessTokenExpiresIn: 15m
  refreshTokenExpiresIn: 168h

ldap:
  url: 	ldap://ldap.mines-ales.fr:389
  #url: ldap://localhost:3890
  baseDN: dc=ema,dc=fr
